language: generic 
sudo: required

services:
    - docker 

before_install:
    - docker build -t react_app -f Dockerfile.dev .

script:
    - docker run -e CI=true react_app npm run test

deploy:
    edge: true 
    provider: elasticbeanstalk
    region: "eu-central-1" 
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-central-1-869589321280"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"