version: '3'
services:
    web:
        build: 
            context: .  #specifiy the directory where the files should be pulled from
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules         # do not try to overwrite / map this module
            - .:/app                    # current_dir:/app

    tests:
        build: 
            context: .  #specifiy the directory where the files should be pulled from
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules         # do not try to overwrite / map this module
            - .:/app                    # current_dir:/app
        command: ["npm","run","test"]

        

